app:
  datasource:
    jdbc:url: jdbc:postgresql://inventory-1.chbvabsbak05.eu-north-1.rds.amazonaws.com:5432/inventorydb
    username: postgres
    password: postgres12345

mybatis:
  config-location: classpath:mybatis-config.xml
  
spring:
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: hainventoryapp@gmail.com
    password: fjqciujtksfemikp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 5000