app:
  datasource:
    jdbc:url: jdbc:postgresql://inventory-1.chbvabsbak05.eu-north-1.rds.amazonaws.com:5432/inventorydb
    username: postgres
    password:

mybatis:
  config-location: classpath:mybatis-config.xml
  
spring:
  mail:
    protocol:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 5000