app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/inventorydb
    username: postgres
    password:
    pool-size: 30

mybatis:
  config-location: classpath:mybatis-config.xml

spring:
  mail:
    protocol:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 5000
