app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/inventorydb
    username: postgres
    password: password
    pool-size: 30

mybatis:
  config-location: classpath:mybatis-config.xml


